
sender_iban: "PK80DUIB0000000094216001"
receiver_iban: "PK61ABPA0010000019474073"
# ─────────────────────────────────────────────────────────────────────────────
# Shared test data for TC011 – TC020
# Edit the values below; they are injected into request JSON files at runtime
# using the ${VARIABLE_NAME} placeholder syntax.
# ─────────────────────────────────────────────────────────────────────────────

# Primary customer identity used across TC011-TC015, TC017, TC019-TC020
CNIC: "2077963780014"
#for postive and negative test cases, we need to use different CNICs for the same customer. So, we have added 3 more CNICs for the same customer.
CNIC2: "1180193082534"
CNIC3: "1174007501014"
CNIC4: "2000163001014"
CNIC5: "1249789001534"
CNIC6: "1030103208756"
CNIC7: "2269006362534"


# Primary alias (mobile) used in TC015-TC017, TC019
MOBILE: "03193675229"

# Primary IBAN used in TC015, TC019
IBAN: "PK15BAHL0993789500034820"


# ─────────────────────────────────────────────────────────────────────────────
# Secondary values used in TC018 (link account for a second customer / alias)
# ─────────────────────────────────────────────────────────────────────────────
CNIC_2: "4240002636655"
MOBILE_2: "01976300225"
IBAN_2: "PK15BPHL71978969500034815"

TIMEOUT_IBAN: "PK27FAYS0110006000039479"
REJECT_IBAN: "PK46TMFB0000000044235680"
TIME_OUT_SBP: "PK46TMFB0000000044235681"
FAILED_IBAN: "PK94CRSM0000003265703141"
TIMEOUT_CBS: "PK27FAYS0110006000039479"
title_fetch_with_payment_iban: "PK94CRSM0000003265703141"
bic_code: "CRSMPKKA"

# Merchant CAS payment data
merchant_account_title: "HASSAN WHEELS"
merchant_dba: "HASSAN WHEELS"
merchant_category_code: "7022"
merchant_bic: "ABPAPKKA"
merchant_iban: "PK26ABPA0020129555440019"
merchant_id_alias: "2604071156570492485"
merchant_currency: "586"
merchant_country: "PK"
merchant_city: "Lahore"
merchant_store_label: "930001763362675"
merchant_terminal_id: "930000007"

# Merchant CAS RTP IDs - update these with RTP IDs provided for each run.
rtp_id: "213eruwpies-dsklfjkslk-q234jfd23-23"
rtp_id_tc016: "213eruwpies-dsklfjkslk-q234jfd23-23"
rtp_id_tc017: "213eruwpies-dsklfjkslk-q234jfd23-24"
rtp_id_tc018: "213eruwpies-dsklfjkslk-q234jfd23-25"
